name: Build and Release

on:
  push:
    branches:
      - "main"
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Install TinyGo
        run: |
          wget https://github.com/tinygo-org/tinygo/releases/download/v0.40.1/tinygo_0.40.1_amd64.deb
          sudo dpkg -i tinygo_0.40.1_amd64.deb

      - name: Download dependencies
        run: go mod tidy && go mod download

      - name: Build plugin
        run: make build

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: navisync.ndp
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
